### ISSUE TITLE
Issues with AllDS2020.ipynb

### ISSUE THREAD

**Issue by rishabhbanga** [AMLResearchProject/ALL-Detection-System-For-Oculus-Rift#10]
**Describe the bug**
Couple of issues

1. FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/ALL-Detection-System-2020/Model/config.json' under Load and print configs section

2. ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required under Sort the data section

**To Reproduce**
1. Run AllDS2020.ipynb
2. Once you fix Issue 1 you'll encounter Issue 2

**Expected behavior**
Notebook should have run completely without issues

**Comment by rishabhbanga** [comment]
Issue 1 can be fixed by changing 
open(root_dir + '/Model/config.json') as confs:
to 
open(root_dir + 'CNN/Model/config.json') as confs:

Also might as well add in the section above it:
cd /content/drive/My Drive/
!git clone -b "0.0.2" https://github.com/AMLResearchProject/ALL-Detection-System-2020.git

Under Sorting Data Section:
Shape is coming as (0,)

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

**Comment by AdamMiltonBarker** [comment]
Thanks @rishabhbanga  no need for cd /content/drive/My Drive/ , instructions already exist in the core README on cloning the repo and the tutorial covers uploading to Drive, this change would mean multiple others that aren't required. User would already of had to upload to be able to clone within Colab.

RE other bugs thanks I will clone again and test now.

**Comment by AdamMiltonBarker** [comment]
OK all issues are solved by adding CNN to the root dir path. My bad thanks for testing @rishabhbanga  Pull request will be ready in a few minutes.

**Comment by AdamMiltonBarker** [comment]
@rishabhbanga  pull request is ready for review mate, let's get this one signed off :)
