### ISSUE TITLE
Can't execute `conda install` from Setup script 

### ISSUE THREAD

**Issue by rishabhbanga** [AMLResearchProject/ALL-Detection-System-For-Oculus-Rift#2]
**Describe the bug**
Trying to use conda install does not work inside a bash script. 

**To Reproduce**
1. Ran sh Script.sh or ./Script.sh on Powershell
2.  See error - Setup.sh: 5: Setup.sh: conda: not found

**Expected behavior**
Script should run without errors

**Screenshots**
NA.

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Command-line interpreter: [Powershell]
 - Version [5.1.19041.1]

**Additional context**
NA

**Comment by rishabhbanga** [comment]
Solution identified and would be push in next commit. Since functions are not exported by default to be made available in subshells, need to  use source ~/anaconda3/etc/profile.d/conda.sh

**Comment by AdamMiltonBarker** [comment]
Thank you @rishabhbanga !

**Comment by AdamMiltonBarker** [comment]
@rishabhbanga  please could test linux also before pushing your updates mate.

**Comment by rishabhbanga** [comment]
Already pushed it, but I'll check it out now.

**Comment by AdamMiltonBarker** [comment]
@rishabhbanga to add to an exist pull request you can commit changes to your fork, as mentioned in your other issue please coul d you add the  documentation. Thanks mate.

**Comment by rishabhbanga** [comment]
Added it here - https://github.com/AMLResearchProject/ALL-Detection-System-2020/pull/5

**Comment by AdamMiltonBarker** [comment]
Thanks @rishabhbanga
