### ISSUE TITLE
python3 doesn't work in Conda

### ISSUE THREAD

**Issue by rishabhbanga** [AMLResearchProject/ALL-Detection-System-For-Oculus-Rift#4]
**Describe the bug**
Any of the commands starting with python3, like python3 AllDS2020.py Train do not work in Conda

**To Reproduce**
1. Follow the steps mentioned in README.md
2. While starting training in Conda environment, run python3 AllDS2020.py Train 
4. See error(s) - Nothing happens or Windows opens up the Store application

**Expected behavior**
Steps should run as expected and mentioned in the README.md file

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Command-line interpreter: [Powershell]
 - Version [5.1.19041.1]

**Additional context**
NA

**Comment by rishabhbanga** [comment]
This obviously would be reproducible in any OS environment since in Conda using python suffices.

**Comment by AdamMiltonBarker** [comment]
@rishabhbanga Thanks I merged this code but noticed there is no documentation for it mate please could you add.

**Comment by rishabhbanga** [comment]
Sure. Added it in pull request https://github.com/AMLResearchProject/ALL-Detection-System-2020/pull/5

**Comment by AdamMiltonBarker** [comment]
Thanks @rishabhbanga
